# Generated by Django 6.0.4 on 2026-05-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='credited',
            field=models.BooleanField(default=False),
        ),
    ]
