# Generated by Django 6.0.4 on 2026-05-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='deducted',
            field=models.BooleanField(default=False),
        ),
    ]
