# Generated by Django 6.0.4 on 2026-05-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_withdrawal_deducted'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='referral_bonus_paid',
            field=models.BooleanField(default=False),
        ),
    ]
