# Generated by Django 6.0.4 on 2026-05-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_investmentplan_userinvestment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinvestment',
            old_name='last_profit_date',
            new_name='last_claim',
        ),
        migrations.AddField(
            model_name='userinvestment',
            name='days_paid',
            field=models.IntegerField(default=0),
        ),
    ]
