# Generated by Django 6.0.4 on 2026-05-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_last_profit_date_userinvestment_last_claim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=12),
            preserve_default=False,
        ),
    ]
