# Generated by Django 6.0.4 on 2026-05-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_transactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
