# Generated by Django 6.0.5 on 2026-05-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_deposit_admin_note_withdrawal_admin_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('deposits_enabled', models.BooleanField(default=True)),
                ('withdrawals_enabled', models.BooleanField(default=True)),
                ('investments_enabled', models.BooleanField(default=True)),
                ('site_announcement', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
