# Generated by Django 6.0.5 on 2026-05-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_owneractionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('Normal', 'Normal'), ('Important', 'Important'), ('Critical', 'Critical')], default='Normal', max_length=20)),
                ('target_audience', models.CharField(choices=[('All', 'All Users'), ('Investors', 'Investors'), ('Active', 'Active Users')], default='All', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
