# Generated by Django 6.0.5 on 2026-06-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_broadcastmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessage',
            name='dismissible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='send_as_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
    ]
