# Generated by Django 6.0.4 on 2026-05-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_claim_streak_customuser_last_streak_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='suspension_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
