# Generated by Django 6.0.5 on 2026-06-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_is_suspended_customuser_suspension_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_email_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
