# Generated by Django 6.0.5 on 2026-06-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_last_email_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='kyc_verified',
            field=models.BooleanField(default=False),
        ),
    ]
