# Generated by Django 6.0.5 on 2026-06-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_kyc_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='withdrawal_pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
